# The URL the site will be built for
base_url = "https://craigmulligan.com"

compile_sass = false
build_search_index = false
hard_link_static = true
feed_filename = "atom.xml"
generate_feed = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "kronuz"

[extra]
# Put all your custom variables here
